# Generated by Django 3.1.3 on 2021-01-17 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import refrigerator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limitRegister', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='賞味・消費期限')),
                ('foodGram', models.PositiveIntegerField(default=0, validators=[refrigerator.models.check_gram])),
                ('volume', models.CharField(default='個', max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refrigerator.food')),
            ],
            options={
                'ordering': ('-limitRegister',),
            },
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refrigerator.foodset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
