# Generated by Django 3.1.3 on 2020-12-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limitRegister', models.DateField(blank=True, null=True, verbose_name='賞味・消費期限')),
                ('foodGram', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refrigerator.food')),
            ],
        ),
    ]
