# Generated by Django 3.1.3 on 2020-12-08 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refrigerator', '0002_foodset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodset',
            options={'ordering': ('-limitRegister',)},
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refrigerator.foodset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
