# Generated by Django 3.1.3 on 2020-12-12 02:41

from django.db import migrations, models
import refrigerator.models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0003_auto_20201208_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodset',
            name='volume',
            field=models.CharField(default='個', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodset',
            name='foodGram',
            field=models.IntegerField(default=0, validators=[refrigerator.models.check_gram]),
        ),
    ]
